### ISSUE TITLE
"Replaying" Vidstack YouTube player causes video to buffer indefinitely

### ISSUE THREAD

**Issue by 96imranahmed** [vidstack/player#1392]
### Current Behavior:

When I `replay` the vidstack player with a YouTube video via button on the bottom left, the video plays initially but then seems to stop buffering permanently. This is reproducible. 

I notice the player dispatches a `waiting` event but nothing seems to happen afterwards.

### Expected Behavior:

The video should buffer normally, just as it does when playing a YouTube video for the first time.

### Steps To Reproduce:

1. Refresh your page and visit the demo link [here](https://www.vidstack.io/player/demo?framework=react&view=player&preset=youtube&config=%7B%22player%22%3A%7B%22src%22%3A%22youtube%2F_cMxraX_5RE%22%2C%22viewType%22%3A%22video%22%2C%22streamType%22%3A%22on-demand%22%2C%22logLevel%22%3A%22warn%22%2C%22crossOrigin%22%3Atrue%2C%22playsInline%22%3Atrue%2C%22title%22%3A%22Sprite+Fight%22%2C%22poster%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fposter.webp%22%2C%22textTracks%22%3A%5B%7B%22src%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fsubs%2Fenglish.vtt%22%2C%22label%22%3A%22English%22%2C%22language%22%3A%22en-US%22%2C%22kind%22%3A%22subtitles%22%2C%22type%22%3A%22vtt%22%2C%22default%22%3Atrue%7D%2C%7B%22src%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fsubs%2Fspanish.vtt%22%2C%22label%22%3A%22Spanish%22%2C%22language%22%3A%22es-ES%22%2C%22kind%22%3A%22subtitles%22%2C%22type%22%3A%22vtt%22%7D%2C%7B%22src%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fchapters.vtt%22%2C%22language%22%3A%22en-US%22%2C%22kind%22%3A%22chapters%22%2C%22type%22%3A%22vtt%22%2C%22default%22%3Atrue%7D%5D%7D%2C%22layout%22%3A%7B%22type%22%3A%22default%22%2C%22thumbnails%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fthumbnails.vtt%22%7D%2C%22hls%22%3A%7B%7D%2C%22dash%22%3A%7B%7D%2C%22events%22%3A%5B%22can-play%22%5D%7D)
2. Play the video from the beginning and then skip to near the end as quickly as possible. Wait until you see the "Pause" icon turn into the "Replay" icon
3. Click "Replay"
4. Wait a few moments. The video starts normally, but then it stops and buffers indefinitely. Controls become unresponsive - trying to pause / unpause does not help. The point where this happens changes based on **how much video you buffered when you originally played it prior to replay.**

### Environment:

Listing out my own environment here just in case it's helpful: 
- Version: "0.6.15" (on my own device) but also occurring on "1.12.8"
- Framework: React
- Browser: Chrome@127
- OS: MacOS Sonomo 14.5

### Anything Else?
<img width="784" alt="image" src="https://github.com/user-attachments/assets/04165777-2290-4046-b5dd-11303a708e86">

**Comment by mihar-22** [comment]
Resolved by #1393.

**Comment by 96imranahmed** [comment]
Hey @mihar-22 , I just installed the latest build via `@vidstack/react@1.12.9` (and have verified that I'm using the latest version in my node_modules with the commit that fixed #1393 ). 

However, the issue here doesn't seem to have been resolved. I can still reproduce this issue consistently.

**Comment by mihar-22** [comment]
I'll double check when I can but it worked on my few tests.

**Comment by mihar-22** [comment]
I can see the issue and I confirmed it's happening on the embed side and not in our player. Not sure how to resolve this at the moment.

**Comment by mikevrpv** [comment]
@mihar-22 Hey, not sure if it's exactly the same issue, but it's easy to reproduce even on demo site: [here](https://vidstack.io/player/demo/?layout=plyr&framework=wc&view=player&preset=youtube&config=%7B%22player%22%3A%7B%22src%22%3A%22youtube%2F_cMxraX_5RE%22%2C%22viewType%22%3A%22video%22%2C%22streamType%22%3A%22on-demand%22%2C%22logLevel%22%3A%22warn%22%2C%22crossOrigin%22%3Atrue%2C%22playsInline%22%3Atrue%2C%22title%22%3A%22Sprite+Fight%22%2C%22poster%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fposter.webp%22%2C%22textTracks%22%3A%5B%7B%22src%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fsubs%2Fenglish.vtt%22%2C%22label%22%3A%22English%22%2C%22language%22%3A%22en-US%22%2C%22kind%22%3A%22subtitles%22%2C%22type%22%3A%22vtt%22%2C%22default%22%3Atrue%7D%2C%7B%22src%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fsubs%2Fspanish.vtt%22%2C%22label%22%3A%22Spanish%22%2C%22language%22%3A%22es-ES%22%2C%22kind%22%3A%22subtitles%22%2C%22type%22%3A%22vtt%22%7D%2C%7B%22src%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fchapters.vtt%22%2C%22language%22%3A%22en-US%22%2C%22kind%22%3A%22chapters%22%2C%22type%22%3A%22vtt%22%2C%22default%22%3Atrue%7D%5D%7D%2C%22layout%22%3A%7B%22type%22%3A%22default%22%2C%22thumbnails%22%3A%22https%3A%2F%2Ffiles.vidstack.io%2Fsprite-fight%2Fthumbnails.vtt%22%7D%2C%22hls%22%3A%7B%7D%2C%22dash%22%3A%7B%7D%2C%22events%22%3A%5B%22can-play%22%5D%7D)

Before starting the video initially, press rapidly several times (let's say 3 subsequent clicks in a row) on a "play" button (like you're impatient while it's initially loading). This will cause player to load indefinitely while blocking all controls at the same time. You can still switch and scrub the timeline and even see the video jumps to the selected time, but it won't ever play again normally. Maybe some bug to look for.
